name: Deploy to Server via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/homagency/htdocs/homagency.ae/backend/backend/
            # Si le dépôt n'existe pas, on le clone
            if [ ! -d ".git" ]; then
              cd ..
              rm -rf backend
              git clone https://github.com/medalimab/backend.git backend
              cd backend
            else
              git pull origin master
            fi
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan route:clear
            php artisan config:clear
            php artisan view:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache